services:
    app-service:
        build: ./services/app
        ports:
            - "4002:4002"
        environment:
            DATABASE_URL: ${DATABASE_URL}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PW: ${REDIS_PW}
            NODE_ENV: production
    user-service:
        build: ./services/users
        ports:
            - "4001:4001"
        environment:
            MONGO_URL: ${MONGO_URL}
    orchestrator:
        build: ./orchestrator
        ports: 
            - "80:4000"
        environment:
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PW: ${REDIS_PW}
            